import { describe, it, expect, vi } from "vitest";
import { z } from "zod";

// Mock the database module
vi.mock("@/server/db", () => ({
  db: {},
}));

// Mock next/headers
vi.mock("next/headers", () => ({
  headers: vi.fn().mockResolvedValue(new Map()),
}));

// Mock auth
vi.mock("@/server/auth", () => ({
  auth: {
    api: {
      getSession: vi.fn().mockResolvedValue(null),
    },
  },
}));

describe("Stock Adjustments", () => {
  describe("stock.adjust mutation logic", () => {
    it("validates non-zero quantity change", () => {
      const schema = z.object({
        batchId: z.string().uuid(),
        productId: z.string().uuid(),
        quantityChange: z
          .number()
          .int()
          .refine((v: number) => v !== 0, {
            message: "Quantity change must be non-zero",
          }),
        reason: z.enum([
          "damage",
          "returns",
          "cycle_count_variance",
          "other",
        ]),
        notes: z.string().optional(),
      });

      // Zero should fail
      const zeroResult = schema.safeParse({
        batchId: "a0000000-0000-4000-8000-000000000001",
        productId: "b0000000-0000-4000-8000-000000000002",
        quantityChange: 0,
        reason: "damage",
      });
      expect(zeroResult.success).toBe(false);

      // Positive should pass
      const positiveResult = schema.safeParse({
        batchId: "a0000000-0000-4000-8000-000000000001",
        productId: "b0000000-0000-4000-8000-000000000002",
        quantityChange: 5,
        reason: "returns",
      });
      expect(positiveResult.success).toBe(true);

      // Negative should pass
      const negativeResult = schema.safeParse({
        batchId: "a0000000-0000-4000-8000-000000000001",
        productId: "b0000000-0000-4000-8000-000000000002",
        quantityChange: -3,
        reason: "damage",
      });
      expect(negativeResult.success).toBe(true);
    });

    it("rejects adjustment that would make quantity negative", async () => {
      // Simulate the adjustment logic
      const currentAvailable = 5;
      const quantityChange = -10;
      const newAvailable = currentAvailable + quantityChange;

      expect(newAvailable).toBeLessThan(0);

      // The router should throw in this case
      const shouldReject = () => {
        if (newAvailable < 0) {
          throw new Error(
            `Cannot reduce below zero. Current available: ${currentAvailable}, requested change: ${quantityChange}`
          );
        }
      };

      expect(shouldReject).toThrow("Cannot reduce below zero");
    });

    it("accepts adjustment that reduces to exactly zero", () => {
      const currentAvailable = 5;
      const quantityChange = -5;
      const newAvailable = currentAvailable + quantityChange;

      expect(newAvailable).toBe(0);
      // Should not throw -- zero is valid (batch becomes depleted)
      expect(() => {
        if (newAvailable < 0) {
          throw new Error("Cannot reduce below zero");
        }
      }).not.toThrow();
    });

    it("sets batch status to depleted when quantity reaches zero", () => {
      const currentAvailable = 5;
      const quantityChange = -5;
      const newAvailable = currentAvailable + quantityChange;
      const newStatus = newAvailable === 0 ? "depleted" : undefined;

      expect(newStatus).toBe("depleted");
    });

    it("does not change status when quantity remains positive", () => {
      const currentAvailable = 10;
      const quantityChange = -3;
      const newAvailable = currentAvailable + quantityChange;
      const newStatus = newAvailable === 0 ? "depleted" : undefined;

      expect(newStatus).toBeUndefined();
      expect(newAvailable).toBe(7);
    });
  });

  describe("stock.adjust mutation - audit logging", () => {
    it("creates adjustment record with user, reason, and timestamp fields", () => {
      const adjustmentRecord = {
        batchId: "a0000000-0000-4000-8000-000000000001",
        productId: "b0000000-0000-4000-8000-000000000002",
        quantityChange: -5,
        reason: "damage" as const,
        notes: "Damaged during transit",
        adjustedBy: "test-user-id",
      };

      expect(adjustmentRecord).toHaveProperty("adjustedBy", "test-user-id");
      expect(adjustmentRecord).toHaveProperty("reason", "damage");
      expect(adjustmentRecord).toHaveProperty("quantityChange", -5);
      expect(adjustmentRecord).toHaveProperty("notes", "Damaged during transit");
      // createdAt is auto-generated by the DB defaultNow()
    });

    it("supports all four reason codes", () => {
      const validReasons = [
        "damage",
        "returns",
        "cycle_count_variance",
        "other",
      ];
      const reasonSchema = z.enum([
        "damage",
        "returns",
        "cycle_count_variance",
        "other",
      ]);

      for (const reason of validReasons) {
        expect(reasonSchema.safeParse(reason).success).toBe(true);
      }

      expect(reasonSchema.safeParse("invalid_reason").success).toBe(false);
    });
  });

  describe("stock.dashboard query", () => {
    it("returns product-level aggregates structure", () => {
      // Verify the expected shape of dashboard response
      const mockDashboardResponse = {
        products: [
          {
            productId: "p1",
            productName: "M12 Anchor Bolt",
            sku: "TRK-MECH-001",
            totalQuantity: 100,
            totalAvailable: 80,
            totalReserved: 20,
            batchCount: 3,
            oldestBatchDate: "2025-01-15",
            nearestExpiry: "2026-06-30",
          },
        ],
        summary: {
          totalProducts: 1,
          totalUnitsAvailable: 80,
          lowStockCount: 0,
          expiringSoon: 0,
        },
      };

      expect(mockDashboardResponse.products).toHaveLength(1);
      expect(mockDashboardResponse.products[0]).toHaveProperty("totalQuantity");
      expect(mockDashboardResponse.products[0]).toHaveProperty("totalAvailable");
      expect(mockDashboardResponse.products[0]).toHaveProperty("totalReserved");
      expect(mockDashboardResponse.products[0]).toHaveProperty("batchCount");
      expect(mockDashboardResponse.summary).toHaveProperty("totalProducts");
      expect(mockDashboardResponse.summary).toHaveProperty("lowStockCount");
      expect(mockDashboardResponse.summary).toHaveProperty("expiringSoon");
    });

    it("computes correct aggregates from multiple batches", () => {
      // Simulate what the SQL aggregation would produce
      const batches = [
        { quantity: 50, quantityAvailable: 40, quantityReserved: 10 },
        { quantity: 30, quantityAvailable: 25, quantityReserved: 5 },
        { quantity: 20, quantityAvailable: 15, quantityReserved: 5 },
      ];

      const totalQuantity = batches.reduce((sum, b) => sum + b.quantity, 0);
      const totalAvailable = batches.reduce(
        (sum, b) => sum + b.quantityAvailable,
        0
      );
      const totalReserved = batches.reduce(
        (sum, b) => sum + b.quantityReserved,
        0
      );

      expect(totalQuantity).toBe(100);
      expect(totalAvailable).toBe(80);
      expect(totalReserved).toBe(20);
      expect(batches.length).toBe(3);
    });

    it("identifies low stock products (< 10 units available)", () => {
      const productStocks = [
        { productId: "p1", totalAvailable: 80 },
        { productId: "p2", totalAvailable: 5 },
        { productId: "p3", totalAvailable: 9 },
        { productId: "p4", totalAvailable: 10 },
      ];

      const lowStock = productStocks.filter((p) => p.totalAvailable < 10);
      expect(lowStock).toHaveLength(2);
      expect(lowStock.map((p) => p.productId)).toEqual(["p2", "p3"]);
    });
  });

  describe("stock.adjustmentHistory query", () => {
    it("returns ordered results with joined data structure", () => {
      const mockHistory = [
        {
          id: "adj-1",
          batchId: "b1",
          torkeBatchId: "TRK-2025-001",
          productId: "p1",
          productName: "M12 Anchor Bolt",
          sku: "TRK-MECH-001",
          quantityChange: -5,
          reason: "damage",
          notes: "Damaged on inspection",
          adjustedBy: "user-123",
          createdAt: new Date("2026-03-04T10:00:00Z"),
        },
        {
          id: "adj-2",
          batchId: "b2",
          torkeBatchId: "TRK-2025-002",
          productId: "p1",
          productName: "M12 Anchor Bolt",
          sku: "TRK-MECH-001",
          quantityChange: 10,
          reason: "returns",
          notes: null,
          adjustedBy: "user-456",
          createdAt: new Date("2026-03-04T09:00:00Z"),
        },
      ];

      // Should be ordered by createdAt DESC (newest first)
      expect(mockHistory[0]!.createdAt.getTime()).toBeGreaterThan(
        mockHistory[1]!.createdAt.getTime()
      );

      // Should have joined data
      expect(mockHistory[0]).toHaveProperty("torkeBatchId");
      expect(mockHistory[0]).toHaveProperty("productName");
      expect(mockHistory[0]).toHaveProperty("sku");
      expect(mockHistory[0]).toHaveProperty("reason");
      expect(mockHistory[0]).toHaveProperty("adjustedBy");
    });

    it("includes both positive and negative quantity changes", () => {
      const adjustments = [
        { quantityChange: -5, reason: "damage" },
        { quantityChange: 10, reason: "returns" },
        { quantityChange: -2, reason: "cycle_count_variance" },
        { quantityChange: 3, reason: "other" },
      ];

      const negative = adjustments.filter((a) => a.quantityChange < 0);
      const positive = adjustments.filter((a) => a.quantityChange > 0);

      expect(negative).toHaveLength(2);
      expect(positive).toHaveLength(2);
    });
  });
});
