/**
 * Database seed script for user accounts.
 *
 * Creates sample users with different roles:
 * - warehouse@torke.co.uk (warehouse staff)
 * - admin@torke.co.uk (admin)
 *
 * Idempotent: checks if user exists before creating.
 * Requires: DATABASE_URL environment variable.
 *
 * Usage: npx tsx scripts/seed-users.ts
 */

import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { eq } from "drizzle-orm";
import bcrypt from "bcrypt";
import { userProfiles } from "../src/server/db/schema/users.js";

// ───────────────────────────────────────────────────────
// Types
// ───────────────────────────────────────────────────────

interface UserSeedData {
  email: string;
  password: string;
  role: string;
}

// ───────────────────────────────────────────────────────
// Database connection
// ───────────────────────────────────────────────────────

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("ERROR: DATABASE_URL environment variable is required.");
  console.error("Set it in .env.local or export it:");
  console.error(
    '  export DATABASE_URL=postgresql://postgres:torke@localhost:5432/torke'
  );
  process.exit(1);
}

const client = postgres(connectionString);
const db = drizzle(client, {
  schema: { userProfiles },
});

// ───────────────────────────────────────────────────────
// Seed logic
// ───────────────────────────────────────────────────────

async function seedUsers(users: UserSeedData[]): Promise<number> {
  console.log(`Seeding ${users.length} users...`);

  let created = 0;
  let skipped = 0;

  for (const user of users) {
    try {
      // Hash the password
      const hashedPassword = await bcrypt.hash(user.password, 10);

      // Note: In a real Better Auth setup, users are created via the auth API.
      // For this seed script, we're directly inserting into the database.
      // The user ID is generated by Better Auth, so we use a deterministic ID
      // based on the email (in production, you'd want to use the actual auth API).

      // Generate a user ID (Better Auth uses UUID format)
      const userId = `user_${user.email.split("@")[0]}`;

      // Try to insert the user profile (this assumes the user table exists in Better Auth)
      // First, let's check if the user already exists
      const existingProfile = await db
        .select({ id: userProfiles.id })
        .from(userProfiles)
        .where(eq(userProfiles.userId, userId))
        .limit(1);

      if (existingProfile.length > 0) {
        console.log(`  = ${user.email} (${user.role}) already exists`);
        skipped++;
        continue;
      }

      // Insert the user profile
      const result = await db
        .insert(userProfiles)
        .values({
          userId,
          role: user.role,
        })
        .returning({ id: userProfiles.id });

      if (result.length > 0) {
        console.log(`  + ${user.email} (${user.role}) -> ${result[0]?.id}`);
        created++;
      }
    } catch (err: any) {
      console.error(`  ERROR creating "${user.email}": ${err.message}`);
    }
  }

  return created;
}

async function seed() {
  console.log("=== Torke User Database Seed ===\n");

  const users: UserSeedData[] = [
    {
      email: "warehouse@torke.co.uk",
      password: "warehouse123",
      role: "warehouse",
    },
    {
      email: "admin@torke.co.uk",
      password: "admin123",
      role: "admin",
    },
  ];

  console.log(`Data loaded: ${users.length} users\n`);

  // Seed users
  const createdCount = await seedUsers(users);

  // Summary
  console.log("\n=== SEED COMPLETE ===");
  console.log(`Users seeded: ${createdCount}/${users.length}`);

  console.log("\nIMPORTANT: Users have been created in the user_profiles table.");
  console.log(
    "To complete user creation, you need to:"
  );
  console.log("1. Manually create accounts in the Better Auth users/accounts tables, OR");
  console.log("2. Use the Better Auth API endpoint to sign up these users");
  console.log("");
  console.log("User credentials for testing:");
  for (const user of users) {
    console.log(`  - ${user.email} / ${user.password} (role: ${user.role})`);
  }

  // Close connection
  await client.end();
}

seed().catch((err) => {
  console.error("Fatal error:", err);
  client.end();
  process.exit(1);
});
